event_codes = {
    'HTY': {'text': 'Heat Advisory',             'icon': '🌡️', 'level': 'advisory'},


    'TOE': {'text': '911 Outage Emergency', 'icon': '⛔', 'level': 'advisory'},
    'ADR': {'text': 'Administrative Message', 'icon': '📋', 'level': 'advisory'},
    'AVW': {'text': 'Avalanche Warning', 'icon': '❄️', 'level': 'warning'},
    'AVA': {'text': 'Avalanche Watch', 'icon': '🏔️', 'level': 'watch'},
    'BHW': {'text': 'Biological Hazard Warning', 'icon': '☣️', 'level': 'warning'},
    'BZW': {'text': 'Blizzard Warning', 'icon': '🌨️', 'level': 'warning'},
    'BLU': {'text': 'Blue Alert', 'icon': '🔵', 'level': 'advisory'},
    'BWW': {'text': 'Boil Water Warning', 'icon': '🚱', 'level': 'warning'},
    'CHW': {'text': 'Chemical Hazard Warning', 'icon': '🧪', 'level': 'warning'},
    'CAE': {'text': 'Child Abduction Emergency', 'icon': '🚨', 'level': 'advisory'},
    'CDW': {'text': 'Civil Danger Warning', 'icon': '⚠️', 'level': 'warning'},
    'CEM': {'text': 'Civil Emergency Message', 'icon': '📢', 'level': 'advisory'},
    'CFW': {'text': 'Coastal Flood Warning', 'icon': '🌊', 'level': 'warning'},
    'CFA': {'text': 'Coastal Flood Watch', 'icon': '🌊', 'level': 'watch'},
    'DEW': {'text': 'Contagious Disease Warning', 'icon': '🦠', 'level': 'warning'},
    'CWW': {'text': 'Contaminated Water Warning', 'icon': '🚱', 'level': 'warning'},
    'DBW': {'text': 'Dam Break Warning', 'icon': '🌊', 'level': 'warning'},
    'DBA': {'text': 'Dam Watch', 'icon': '🌊', 'level': 'watch'},
    'DMO': {'text': 'Demo Warning', 'icon': '🛠️', 'level': 'warning'},
    'DSW': {'text': 'Dust Storm Warning', 'icon': '🌪️', 'level': 'warning'},
    'EQW': {'text': 'Earthquake Warning', 'icon': '🌎', 'level': 'warning'},
    'EAN': {'text': 'Emergency Action Notification', 'icon': '🚨', 'level': 'advisory'},
    'EAT': {'text': 'Emergency Action Termination', 'icon': '🔚', 'level': 'advisory'},
    'EVI': {'text': 'Evacuation Immediate', 'icon': '🏃‍♂️', 'level': 'advisory'},
    'EVA': {'text': 'Evacuation Watch', 'icon': '🏃‍♂️', 'level': 'watch'},
    'EWW': {'text': 'Extreme Wind Warning', 'icon': '🚩', 'level': 'warning'},
    'FRW': {'text': 'Fire Warning', 'icon': '🔥', 'level': 'warning'},
    'FFS': {'text': 'Flash Flood Statement', 'icon': '🌧️', 'level': 'advisory'},
    'FFW': {'text': 'Flash Flood Warning', 'icon': '🌊', 'level': 'warning'},
    'FFA': {'text': 'Flash Flood Watch', 'icon': '🌊', 'level': 'watch'},
    'FSW': {'text': 'Flash Freeze Warning', 'icon': '❄️', 'level': 'warning'},
    'FLS': {'text': 'Flood Statement', 'icon': '🌧️', 'level': 'advisory'},
    'FLW': {'text': 'Flood Warning', 'icon': '🌊', 'level': 'warning'},
    'FLA': {'text': 'Flood Watch', 'icon': '🌊', 'level': 'watch'},
    'FCW': {'text': 'Food Contamination Warning', 'icon': '☣️', 'level': 'warning'},
    'FZW': {'text': 'Freeze Warning', 'icon': '❄️', 'level': 'warning'},
    'HMW': {'text': 'Hazardous Materials Warning', 'icon': '⚠️', 'level': 'warning'},
    'HWW': {'text': 'High Wind Warning', 'icon': '🚩', 'level': 'warning'},
    'HWA': {'text': 'High Wind Watch', 'icon': '🍃', 'level': 'watch'},
    'HLS': {'text': 'Hurricane Statement', 'icon': '🌀', 'level': 'advisory'},
    'HUW': {'text': 'Hurricane Warning', 'icon': '🌀', 'level': 'warning'},
    'HUA': {'text': 'Hurricane Watch', 'icon': '🌀', 'level': 'watch'},
    'IBW': {'text': 'Iceberg Warning', 'icon': '🧊', 'level': 'warning'},
    'IFW': {'text': 'Industrial Fire Warning', 'icon': '🏭🔥', 'level': 'warning'},
    'LSW': {'text': 'Land Slide Warning', 'icon': '🪨', 'level': 'warning'},
    'LEW': {'text': 'Law Enforcement Warning', 'icon': '🚓', 'level': 'warning'},
    'LAE': {'text': 'Local Area Emergency', 'icon': '📢', 'level': 'advisory'},
    'NAT': {'text': 'National Audible Test', 'icon': '🔔', 'level': 'advisory'},
    'NIC': {'text': 'National Information Center', 'icon': 'ℹ️', 'level': 'advisory'},
    'NPT': {'text': 'National Periodic Test', 'icon': '📝', 'level': 'advisory'},
    'NST': {'text': 'National Silent Test', 'icon': '🔕', 'level': 'advisory'},
    'NMN': {'text': 'Network Message Notification', 'icon': '📡', 'level': 'advisory'},
    'NUW': {'text': 'Nuclear Plant Warning', 'icon': '☢️', 'level': 'warning'},
    'POS': {'text': 'Power Outage Statement', 'icon': '🔌', 'level': 'advisory'},
    'RHW': {'text': 'Radiological Hazard Warning', 'icon': '☢️', 'level': 'warning'},
    'RMT': {'text': 'Required Monthly Test', 'icon': '📅', 'level': 'advisory'},
    'RWT': {'text': 'Required Weekly Test', 'icon': '📆', 'level': 'advisory'},
    'SVR': {'text': 'Severe Thunderstorm Warning', 'icon': '⛈️', 'level': 'warning'},
    'SVA': {'text': 'Severe Thunderstorm Watch', 'icon': '⛈️', 'level': 'watch'},
    'SVS': {'text': 'Severe Weather Statement', 'icon': '⚠️', 'level': 'advisory'},
    'SPW': {'text': 'Shelter in Place Warning', 'icon': '🏠', 'level': 'warning'},
    'SQW': {'text': 'Snow Squall Warning', 'icon': '🌨️', 'level': 'warning'},
    'SMW': {'text': 'Special Marine Warning', 'icon': '🚤', 'level': 'warning'},
    'SPS': {'text': 'Special Weather Statement', 'icon': '📢', 'level': 'advisory'},
    'SSW': {'text': 'Storm Surge Warning', 'icon': '🌊', 'level': 'warning'},
    'SSA': {'text': 'Storm Surge Watch', 'icon': '🌊', 'level': 'watch'},
    'TOR': {'text': 'Tornado Warning', 'icon': '🌪️', 'level': 'warning'},
    'TOA': {'text': 'Tornado Watch', 'icon': '🌪️', 'level': 'watch'},
    'TRW': {'text': 'Tropical Storm Warning', 'icon': '🌀', 'level': 'warning'},
    'TRA': {'text': 'Tropical Storm Watch', 'icon': '🌀', 'level': 'watch'},
    'TSW': {'text': 'Tsunami Warning', 'icon': '🌊', 'level': 'warning'},
    'TSA': {'text': 'Tsunami Watch', 'icon': '🌊', 'level': 'watch'},
    'VOW': {'text': 'Volcano Warning', 'icon': '🌋', 'level': 'warning'},
    'WFW': {'text': 'Wild Fire Warning', 'icon': '🔥', 'level': 'warning'},
    'WFA': {'text': 'Wild Fire Watch', 'icon': '🔥', 'level': 'watch'},
    'WSW': {'text': 'Winter Storm Warning', 'icon': '❄️', 'level': 'warning'},
    'WSA': {'text': 'Winter Storm Watch', 'icon': '❄️', 'level': 'watch'}
}

